[build]
  functions = "netlify/functions"
  publish = "dist"
  command = "npm run build"
  ignore = ".bolt/ .netlify/"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/imports/the-cube/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[edge_functions]]
  path = "/.netlify/functions/elevenlabs-websocket"
  function = "elevenlabs-websocket"

[[edge_functions]]
  path = "/.netlify/functions/ably-bridge"
  function = "ably-elevenlabs-bridge"