services:
  - type: web
    name: neuraplay-ai-platform
    env: node
    buildCommand: npm install && npm run build:render
    startCommand: npm run start:render
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: true
      - key: VITE_PLATFORM
        value: render
      - key: VITE_ABLY_API_KEY
        sync: false
      - key: VITE_ELEVENLABS_API_KEY
        sync: false
      - key: VITE_ASSEMBLYAI_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: Neuraplay
        sync: false
      - key: ASSEMBLYAI_API_KEY
        sync: false
      - key: ASSEMBLY_API_KEY
        sync: false
      - key: hf_token
        sync: false
      - key: ELEVENLABS_AGENT_ID
        value: agent_2201k13zjq5nf9faywz14701hyhb
    healthCheckPath: /
    autoDeploy: true 